[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.21"
auto_detect_solc = false
optimizer = true
optimizer_runs = 1_000
gas_limit = 100_000_000
gas_reposts = ["*"]
evm_version = "shanghai"


[fmt]
line_length = 100 

remappings = [
    "solady/src/=lib/solady/src/",
]
